# Generated by Django 5.2.14 on 2026-05-28 21:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('vendors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('role', models.CharField(blank=True, help_text="e.g. 'Backend Engineer', 'Data Analyst'", max_length=120)),
                ('description', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, max_length=120)),
                ('is_remote', models.BooleanField(default=False)),
                ('openings', models.PositiveIntegerField(default=1)),
                ('budget_min', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('budget_max', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('budget_currency', models.CharField(default='EUR', max_length=8)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=12)),
                ('status', models.CharField(choices=[('open', 'Open'), ('hold', 'Hold'), ('closing', 'Closing'), ('closed', 'Closed')], default='open', max_length=12)),
                ('target_close_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_vendors', models.ManyToManyField(blank=True, related_name='jobs', to='vendors.vendoraccount')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jobs', to='clients.clientaccount')),
                ('owner', models.ForeignKey(blank=True, limit_choices_to={'role__in': ['admin', 'hr']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='jobs_job_status_7d017a_idx'), models.Index(fields=['client', 'status'], name='jobs_job_client__3a6f6e_idx'), models.Index(fields=['owner'], name='jobs_job_owner_i_90573d_idx')],
            },
        ),
    ]
