# Generated by Django 5.2.14 on 2026-05-28 21:17

import candidates.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('vendors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, db_index=True, max_length=254)),
                ('phone', models.CharField(blank=True, db_index=True, max_length=40)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('current_company', models.CharField(blank=True, max_length=200)),
                ('current_title', models.CharField(blank=True, max_length=200)),
                ('total_experience_years', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('notice_period_days', models.PositiveIntegerField(blank=True, null=True)),
                ('current_ctc', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('expected_ctc', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('ctc_currency', models.CharField(default='EUR', max_length=8)),
                ('skills_csv', models.TextField(blank=True, help_text='Comma-separated skills')),
                ('summary', models.TextField(blank=True)),
                ('source', models.CharField(blank=True, help_text='LinkedIn, Naukri, Vendor referral, etc.', max_length=80)),
                ('stage', models.CharField(choices=[('parsed', 'Parsed'), ('hr_review', 'HR Review'), ('submitted', 'Submitted'), ('client_review', 'Client Review'), ('interview', 'Interview'), ('offer', 'Offer'), ('joined', 'Joined'), ('rejected', 'Rejected'), ('hold', 'Hold')], default='parsed', max_length=20)),
                ('duplicate_status', models.CharField(choices=[('unique', 'Unique'), ('possible', 'Possible duplicate'), ('duplicate', 'Confirmed duplicate')], default='unique', max_length=12)),
                ('parse_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=12)),
                ('parse_error', models.CharField(blank=True, max_length=400)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidates', to='clients.clientaccount')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_candidates', to=settings.AUTH_USER_MODEL)),
                ('duplicate_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duplicates', to='candidates.candidate')),
                ('owner', models.ForeignKey(blank=True, limit_choices_to={'role__in': ['admin', 'hr']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_candidates', to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidates', to='vendors.vendoraccount')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='CandidateNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidate_notes', to=settings.AUTH_USER_MODEL)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='candidates.candidate')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClientPacket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=candidates.models.packet_upload_path)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packets', to='candidates.candidate')),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_packets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='ResumeFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=candidates.models.resume_upload_path)),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('content_type', models.CharField(blank=True, max_length=80)),
                ('size_bytes', models.PositiveIntegerField(default=0)),
                ('extracted_text', models.TextField(blank=True)),
                ('text_hash', models.CharField(blank=True, db_index=True, max_length=64)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to='candidates.candidate')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_resumes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='StageHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_stage', models.CharField(choices=[('parsed', 'Parsed'), ('hr_review', 'HR Review'), ('submitted', 'Submitted'), ('client_review', 'Client Review'), ('interview', 'Interview'), ('offer', 'Offer'), ('joined', 'Joined'), ('rejected', 'Rejected'), ('hold', 'Hold')], max_length=20)),
                ('to_stage', models.CharField(choices=[('parsed', 'Parsed'), ('hr_review', 'HR Review'), ('submitted', 'Submitted'), ('client_review', 'Client Review'), ('interview', 'Interview'), ('offer', 'Offer'), ('joined', 'Joined'), ('rejected', 'Rejected'), ('hold', 'Hold')], max_length=20)),
                ('note', models.CharField(blank=True, max_length=400)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_history', to='candidates.candidate')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stage_changes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-changed_at'],
            },
        ),
        migrations.AddIndex(
            model_name='candidate',
            index=models.Index(fields=['stage'], name='candidates__stage_626629_idx'),
        ),
        migrations.AddIndex(
            model_name='candidate',
            index=models.Index(fields=['client'], name='candidates__client__4203c1_idx'),
        ),
        migrations.AddIndex(
            model_name='candidate',
            index=models.Index(fields=['vendor'], name='candidates__vendor__7bcf5b_idx'),
        ),
        migrations.AddIndex(
            model_name='candidate',
            index=models.Index(fields=['owner'], name='candidates__owner_i_8dd607_idx'),
        ),
        migrations.AddIndex(
            model_name='candidate',
            index=models.Index(fields=['duplicate_status'], name='candidates__duplica_913ccd_idx'),
        ),
    ]
