# Generated by Django 5.2.14 on 2026-05-28 21:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('candidates', '0001_initial'),
        ('clients', '0001_initial'),
        ('jobs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('shortlisted', 'Shortlisted'), ('rejected', 'Rejected'), ('interview', 'Interview'), ('hold', 'Hold'), ('offer', 'Offer'), ('joined', 'Joined')], default='pending', max_length=16)),
                ('vendor_state', models.CharField(choices=[('ready', 'Ready'), ('review', 'Review'), ('duplicate', 'Duplicate')], default='ready', max_length=12)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('last_status_at', models.DateTimeField(auto_now=True)),
                ('note', models.CharField(blank=True, max_length=300)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='candidates.candidate')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submissions', to='clients.clientaccount')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='jobs.job')),
                ('packet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submissions', to='candidates.clientpacket')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submissions_made', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='FeedbackEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('pending', 'Pending'), ('shortlisted', 'Shortlisted'), ('rejected', 'Rejected'), ('interview', 'Interview'), ('hold', 'Hold'), ('offer', 'Offer'), ('joined', 'Joined')], max_length=16)),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback_given', to=settings.AUTH_USER_MODEL)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_events', to='submissions.submission')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['status'], name='submissions_status_c2b4f2_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['client', 'status'], name='submissions_client__14ebf7_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['job'], name='submissions_job_id_2d6849_idx'),
        ),
    ]
