import { Document, Page, Text, View, StyleSheet, renderToBuffer } from "@react-pdf/renderer";

const styles = StyleSheet.create({
  page: { padding: 40, fontFamily: "Helvetica", fontSize: 11, color: "#0f172a" },
  brand: { fontSize: 9, color: "#64748b", letterSpacing: 1, textTransform: "uppercase", marginBottom: 4 },
  refId: { fontSize: 9, color: "#64748b", marginBottom: 18 },
  name: { fontSize: 22, fontWeight: 700, marginBottom: 4, color: "#0f172a" },
  title: { fontSize: 12, color: "#475569", marginBottom: 16 },
  divider: { borderBottomWidth: 1, borderBottomColor: "#e6ebf2", marginVertical: 12 },
  sectionTitle: { fontSize: 10, color: "#64748b", textTransform: "uppercase", letterSpacing: 1, marginBottom: 6 },
  body: { fontSize: 11, lineHeight: 1.5, color: "#0f172a" },
  kpiRow: { flexDirection: "row", flexWrap: "wrap", marginBottom: 8 },
  kpiBox: { width: "50%", paddingVertical: 4 },
  kpiLabel: { fontSize: 9, color: "#94a3b8", textTransform: "uppercase", letterSpacing: 1 },
  kpiValue: { fontSize: 12, color: "#0f172a", marginTop: 1, fontWeight: 700 },
  pillRow: { flexDirection: "row", flexWrap: "wrap", gap: 4 },
  pill: { backgroundColor: "#eff6ff", color: "#1d4ed8", fontSize: 9, paddingHorizontal: 6, paddingVertical: 2, borderRadius: 4, marginRight: 4, marginBottom: 4 },
  footer: { position: "absolute", bottom: 24, left: 40, right: 40, fontSize: 8, color: "#94a3b8", textAlign: "center" },
});

export type PacketCandidate = {
  refId: string;
  fullName: string;
  location: string | null;
  currentTitle: string | null;
  experienceYears: string | null;
  noticePeriodDays: number | null;
  currentCtc: string | null;
  expectedCtc: string | null;
  summary: string | null;
  skills: string[];
};

function fmtCtc(v: string | null) {
  if (!v) return "—";
  const n = Number(v);
  if (Number.isNaN(n)) return v;
  return n.toLocaleString("en-IN", { maximumFractionDigits: 0 });
}

export function PacketDoc({ candidate }: { candidate: PacketCandidate }) {
  return (
    <Document>
      <Page size="A4" style={styles.page}>
        <Text style={styles.brand}>Tru Hyre · Candidate Packet</Text>
        <Text style={styles.refId}>Reference ID: {candidate.refId}</Text>

        <Text style={styles.name}>{candidate.fullName}</Text>
        <Text style={styles.title}>
          {[candidate.currentTitle, candidate.location].filter(Boolean).join(" · ") || "Candidate"}
        </Text>

        <View style={styles.divider} />

        <Text style={styles.sectionTitle}>Snapshot</Text>
        <View style={styles.kpiRow}>
          <View style={styles.kpiBox}>
            <Text style={styles.kpiLabel}>Experience</Text>
            <Text style={styles.kpiValue}>{candidate.experienceYears ? `${candidate.experienceYears} yrs` : "—"}</Text>
          </View>
          <View style={styles.kpiBox}>
            <Text style={styles.kpiLabel}>Notice period</Text>
            <Text style={styles.kpiValue}>{candidate.noticePeriodDays ? `${candidate.noticePeriodDays} days` : "—"}</Text>
          </View>
          <View style={styles.kpiBox}>
            <Text style={styles.kpiLabel}>Current CTC</Text>
            <Text style={styles.kpiValue}>{fmtCtc(candidate.currentCtc)}</Text>
          </View>
          <View style={styles.kpiBox}>
            <Text style={styles.kpiLabel}>Expected CTC</Text>
            <Text style={styles.kpiValue}>{fmtCtc(candidate.expectedCtc)}</Text>
          </View>
        </View>

        {candidate.summary && (
          <>
            <View style={styles.divider} />
            <Text style={styles.sectionTitle}>Summary</Text>
            <Text style={styles.body}>{candidate.summary}</Text>
          </>
        )}

        {candidate.skills.length > 0 && (
          <>
            <View style={styles.divider} />
            <Text style={styles.sectionTitle}>Skills</Text>
            <View style={styles.pillRow}>
              {candidate.skills.map((s) => (
                <Text key={s} style={styles.pill}>{s}</Text>
              ))}
            </View>
          </>
        )}

        <Text style={styles.footer}>
          Sanitized for client review · Contact details withheld · Generated by Tru Hyre
        </Text>
      </Page>
    </Document>
  );
}

export async function renderPacketPdf(candidate: PacketCandidate): Promise<Buffer> {
  return renderToBuffer(<PacketDoc candidate={candidate} />);
}
