import { Document, Page, Text, View, StyleSheet, renderToBuffer } from "@react-pdf/renderer";

const styles = StyleSheet.create({
  page: { padding: 40, fontFamily: "Helvetica", fontSize: 11, color: "#0f172a" },
  brand: { fontSize: 9, color: "#64748b", letterSpacing: 1, textTransform: "uppercase", marginBottom: 4 },
  refId: { fontSize: 9, color: "#64748b", marginBottom: 18 },
  name: { fontSize: 22, fontWeight: 700, marginBottom: 4, color: "#0f172a" },
  title: { fontSize: 12, color: "#475569", marginBottom: 16 },
  divider: { borderBottomWidth: 1, borderBottomColor: "#e6ebf2", marginVertical: 12 },
  sectionTitle: { fontSize: 10, color: "#64748b", textTransform: "uppercase", letterSpacing: 1, marginBottom: 6 },
  body: { fontSize: 11, lineHeight: 1.5, color: "#0f172a" },
  kpiRow: { flexDirection: "row", flexWrap: "wrap", marginBottom: 8 },
  kpiBox: { width: "50%", paddingVertical: 4 },
  kpiLabel: { fontSize: 9, color: "#94a3b8", textTransform: "uppercase", letterSpacing: 1 },
  kpiValue: { fontSize: 12, color: "#0f172a", marginTop: 1, fontWeight: 700 },
  pillRow: { flexDirection: "row", flexWrap: "wrap", gap: 4 },
  pill: { backgroundColor: "#eff6ff", color: "#1d4ed8", fontSize: 9, paddingHorizontal: 6, paddingVertical: 2, borderRadius: 4, marginRight: 4, marginBottom: 4 },
  footer: { position: "absolute", bottom: 24, left: 40, right: 40, fontSize: 8, color: "#94a3b8", textAlign: "center" },
});

export type PacketCandidate = {
  refId: string;
  fullName: string;
  location: string | null;
  currentTitle: string | null;
  experienceYears: string | null;
  noticePeriodDays: number | null;
  currentCtc: string | null;
  expectedCtc: string | null;
  summary: string | null;
  skills: string[];
};

function fmtCtc(v: string | null) {
  if (!v) return "—";
  const n = Number(v);
  if (Number.isNaN(n)) return v;
  return n.toLocaleString("en-IN", { maximumFractionDigits: 0 });
}

export function PacketDoc({ candidate }: { candidate: PacketCandidate }) {
  return (
    <Document>
      <Page size="A4" style={styles.page}>
        <Text style={styles.brand}>Tru Hyre · Candidate Packet</Text>
        <Text style={styles.refId}>Reference ID: {candidate.refId}</Text>

        <Text style={styles.name}>{candidate.fullName}</Text>
        <Text style={styles.title}>
          {[candidate.currentTitle, candidate.location].filter(Boolean).join(" · ") || "Candidate"}
        </Text>

        <View style={styles.divider} />

        <Text style={styles.sectionTitle}>Snapshot</Text>
        <View style={styles.kpiRow}>
          <View style={styles.kpiBox}>
            <Text style={styles.kpiLabel}>Experience</Text>
            <Text style={styles.kpiValue}>{candidate.experienceYears ? `${candidate.experienceYears} yrs` : "—"}</Text>
          </View>
          <View style={styles.kpiBox}>
            <Text style={styles.kpiLabel}>Notice period</Text>
            <Text style={styles.kpiValue}>{candidate.noticePeriodDays ? `${candidate.noticePeriodDays} days` : "—"}</Text>
          </View>
          <View style={styles.kpiBox}>
            <Text style={styles.kpiLabel}>Current CTC</Text>
            <Text style={styles.kpiValue}>{fmtCtc(candidate.currentCtc)}</Text>
          </View>
          <View style={styles.kpiBox}>
            <Text style={styles.kpiLabel}>Expected CTC</Text>
            <Text style={styles.kpiValue}>{fmtCtc(candidate.expectedCtc)}</Text>
          </View>
        </View>

        {candidate.summary && (
          <>
            <View style={styles.divider} />
            <Text style={styles.sectionTitle}>Summary</Text>
            <Text style={styles.body}>{candidate.summary}</Text>
          </>
        )}

        {candidate.skills.length > 0 && (
          <>
            <View style={styles.divider} />
            <Text style={styles.sectionTitle}>Skills</Text>
            <View style={styles.pillRow}>
              {candidate.skills.map((s) => (
                <Text key={s} style={styles.pill}>{s}</Text>
              ))}
            </View>
          </>
        )}

        <Text style={styles.footer}>
          Sanitized for client review · Contact details withheld · Generated by Tru Hyre
        </Text>
      </Page>
    </Document>
  );
}

export async function renderPacketPdf(candidate: PacketCandidate): Promise<Buffer> {
  return renderToBuffer(<PacketDoc candidate={candidate} />);
}

// ---------- Offer letter ----------

export type OfferLetterData = {
  candidateName: string;
  refId: string;
  title: string | null;
  ctc: string | null;
  currency: string;
  joiningDate: string | null;
  companyName: string;
  signerName: string;
  dateStr: string;
};

const offerStyles = StyleSheet.create({
  page: { padding: 56, fontFamily: "Helvetica", fontSize: 11, color: "#0f172a", lineHeight: 1.6 },
  brand: { fontSize: 9, color: "#64748b", letterSpacing: 1, textTransform: "uppercase", marginBottom: 24 },
  h1: { fontSize: 18, fontWeight: 700, marginBottom: 4 },
  meta: { fontSize: 9, color: "#64748b", marginBottom: 24 },
  para: { fontSize: 11, marginBottom: 12 },
  termRow: { flexDirection: "row", marginBottom: 4 },
  termLabel: { width: 130, color: "#64748b" },
  termVal: { fontWeight: 700 },
  sign: { marginTop: 40 },
  footer: { position: "absolute", bottom: 24, left: 56, right: 56, fontSize: 8, color: "#94a3b8", textAlign: "center" },
});

function OfferDoc({ d }: { d: OfferLetterData }) {
  return (
    <Document>
      <Page size="A4" style={offerStyles.page}>
        <Text style={offerStyles.brand}>{d.companyName} · Offer of Employment</Text>
        <Text style={offerStyles.h1}>Dear {d.candidateName},</Text>
        <Text style={offerStyles.meta}>{d.dateStr} · Ref {d.refId}</Text>

        <Text style={offerStyles.para}>
          We are delighted to offer you the position of {d.title || "the role discussed"} at {d.companyName}.
          This letter sets out the principal terms of our offer.
        </Text>

        <View style={offerStyles.termRow}>
          <Text style={offerStyles.termLabel}>Position</Text>
          <Text style={offerStyles.termVal}>{d.title || "—"}</Text>
        </View>
        <View style={offerStyles.termRow}>
          <Text style={offerStyles.termLabel}>Compensation</Text>
          <Text style={offerStyles.termVal}>{d.ctc ? `${d.currency} ${Number(d.ctc).toLocaleString()}` : "As discussed"}</Text>
        </View>
        <View style={offerStyles.termRow}>
          <Text style={offerStyles.termLabel}>Proposed start date</Text>
          <Text style={offerStyles.termVal}>{d.joiningDate || "To be confirmed"}</Text>
        </View>

        <Text style={[offerStyles.para, { marginTop: 16 }]}>
          This offer is contingent on the usual pre-employment checks. We are excited about the contribution
          you will make and look forward to welcoming you to the team.
        </Text>

        <View style={offerStyles.sign}>
          <Text style={offerStyles.para}>Sincerely,</Text>
          <Text style={offerStyles.termVal}>{d.signerName}</Text>
          <Text style={{ color: "#64748b" }}>{d.companyName}</Text>
        </View>

        <Text style={offerStyles.footer}>Generated by Tru Hyre · This document is a non-binding summary pending a formal contract.</Text>
      </Page>
    </Document>
  );
}

export async function renderOfferLetterPdf(d: OfferLetterData): Promise<Buffer> {
  return renderToBuffer(<OfferDoc d={d} />);
}
